all:
	cd gtkapplication && gomake
	cd standardmain && gomake
	cd button_box && gomake
	cd entry_buffer && gomake
	cd dialog && gomake
	cd list_store && gomake
	cd entry_completion && gomake
	cd assistant && gomake
	cd combobox && gomake
	cd textview && gomake
	cd menu && gomake

clean:
	cd gtkapplication && gomake clean
	cd standardmain && gomake clean
	cd button_box && gomake clean
	cd entry_buffer && gomake clean
	cd dialog && gomake clean
	cd list_store && gomake clean
	cd entry_completion && gomake clean
	cd assistant && gomake clean
	cd combobox && gomake clean
	cd textview && gomake clean
	cd menu && gomake clean
