all:
	cd gtkapplication && gomake
	cd standardmain && gomake
	cd button_box && gomake
	cd entry_buffer && gomake

clean:
	cd gtkapplication && gomake clean
	cd standardmain && gomake clean
	cd button_box && gomake clean
	cd entry_buffer && gomake clean
