include $(GOROOT)/src/Make.inc

TARG     = github.com/norisatir/go-gtk3/gtk3
CGOFILES = gtktypes.go gtk3.go window.go widget.go container.go button.go application.go box.go label.go \
		   frame.go dialog.go

include $(GOROOT)/src/Make.pkg
